### ISSUE TITLE
iOS TikiClient email authentication

### ISSUE THREAD

**Issue by ricardobrg** [tiki/publish#16]
### Description

Implement the methods with TIikiClient.email which handles the email authentication services with Gmail and Outlook

### Issues

- [x] tiki/publish-client-ios/issues/2
- [x] tiki/publish-client-ios/issues/3
- [x] tiki/publish-client-ios/issues/4
- [x] tiki/publish-client-ios/issues/5
- [x] tiki/publish-client-ios/issues/6

**Comment by ricardobrg** [comment]
moved to #26
