### ISSUE TITLE
iOS TikiClient capture

### ISSUE THREAD

**Issue by ricardobrg** [tiki/publish#18]
### Description

Implement the TikiClient.capture methods which are responsible for capturing data to be published.

### Issues

- [x] tiki/publish-client-ios#7
- [x] tiki/publish-client-ios#8
- [x] tiki/publish-client-ios#9
- [x] tiki/publish-client-ios#10

### Confirm

- [X] Yeah dude.

**Comment by ricardobrg** [comment]
moved to #26
