### ISSUE TITLE
Android TikiClient capture 

### ISSUE THREAD

**Issue by ricardobrg** [tiki/publish#19]
### Description

Implement the TikiClient.capture methods which are responsible for capturing data to be published.

### Issues

- [x] tiki/publish-client-android#7
- [x] tiki/publish-client-android#8
- [x] tiki/publish-client-android#9
- [x] tiki/publish-client-android#10

### Confirm

- [X] Yeah dude.

**Comment by ricardobrg** [comment]
moved to #27
