### ISSUE TITLE
iOS Client Lib

### ISSUE THREAD

**Issue by ricardobrg** [tiki/publish#26]
### Description

# TIKI Client Library - iOS Specification

## Technologies Used

1. **Language:** Swift
2. **Networking:** URLSession for HTTP communication
3. **Authentication:** AppAuth for OAuth2
4. **Encrypted Storage:** Keychain for secure storage
5. **Storage:** UserDefaults for small non-sensitive key-value pairs and the filesystem for lengthy information, like the index of email IDs.
6. **Camera Integration:** AVFoundation for receipt image capture
7. **UI Components:** SwiftUI

## Library Structure

1. **TikiClient:** The primary entry point for the TIKI Client Library.

2. **TikiClient.auth:** Handles authentication, token retrieval, revocation, and refresh.

3. **TikiClient.license:** Manages user licenses, including creation, retrieval, revocation, and verification.

4. **TikiClient.email:** Manages email-related operations such as adding, retrieving, and removing email accounts.

5. **TikiClient.capture:** Deals with capturing receipt images, downloading and publishing email receipt data, uploading receipt images, and checking publishing status.

6. **TikiClient.clo:** Handles card-linked offers, including adding cards, retrieving offers, getting user rewards, and publishing transaction information.

### TikiClient UI
- [x] tiki/publish-client-ios/issues/31

  - [x] tiki/publish-client-ios/issues/32
  - [x] tiki/publish-client-ios/issues/15
  - [x] tiki/publish-client-ios/issues/16
  - [x] tiki/publish-client-ios/issues/17
  - [x] tiki/publish-client-ios/issues/18
  - [x] tiki/publish-client-ios/issues/19

### TikiClient.email

- [x] tiki/publish-client-ios/issues/4
- [x] tiki/publish-client-ios/issues/5
- [x] tiki/publish-client-ios/issues/6
- [x] tiki/publish-client-ios/issues/8
- [x] tiki/publish-client-ios/issues/9
- [x] tiki/publish-client-ios/issues/10

### TikiClient.license

- [x] tiki/publish-client-ios/issues/20
- [x] tiki/publish-client-ios/issues/21
- [x] tiki/publish-client-ios/issues/22
- [x] tiki/publish-client-ios/issues/23

### TikiClient.auth

  - [x] tiki/publish-client-ios/issues/37
  - [x] tiki/publish-client-ios/issues/38
  - [x] tiki/publish-client-ios/issues/39
