### ISSUE TITLE
Android Client lib

### ISSUE THREAD

**Issue by ricardobrg** [tiki/publish#27]
### Description

# TIKI Client Library - Android Specification

## Technologies Used

1. **Language:** Kotlin
2. **Networking:** Retrofit for HTTP communication
3. **Authentication:** AppAuth for OAuth2
4. **Encrypted Storage:** Secure storage with EncryptedSharedPreferences
5. **Storage** SharedPreferences will be used for small non-sensitive key-value pairs and the filesystem will be used for lengthy information, like index of email ids.
6. **Camera Integration:** Android Camera API for receipt image capture
7. **UI Components:** Jetpack Compose

## Library Structure

1. **TikiClient:** The primary entry point for the TIKI Client Library.

2. **TikiClient.auth:** Handles authentication, token retrieval, revocation, and refresh.

3. **TikiClient.license:** Manages user licenses, including creation, retrieval, revocation, and verification.

4. **TikiClinet.email:** Manages email-related operations such as adding, retrieving, and removing email accounts.

5. **TikiClient.capture:** Deals with capturing receipt images, downloading and publishing email receipt data, uploading receipt images, and checking publishing status.

6. **TikiClient.clo:** Handles card-linked offers, including adding cards, retrieving offers, getting user rewards, and publishing transaction information.

### TikiClient.ui

- [x] tiki/publish#30
- [x] tiki/publish-client-android/issues/15
- [x] tiki/publish-client-android#32
- [x] tiki/publish-client-android#33
- [x] tiki/publish-client-android/issues/16
- [x] tiki/publish-client-android/issues/17
- [x] tiki/publish-client-android/issues/18
- [x] tiki/publish-client-android/issues/19

### TikiClient.license

- [x] tiki/publish-client-android/issues/20
- [x] tiki/publish-client-android/issues/21
- [x] tiki/publish-client-android/issues/22
- [x] tiki/publish-client-android/issues/23

### TikiClient.auth

- [x] tiki/publish-client-android/issues/37
- [x] tiki/publish-client-android/issues/39
- [x] tiki/publish-client-android/issues/38

### TikiClient.email

- [x] tiki/publish-client-android/issues/3
- [x] tiki/publish-client-android/issues/4
- [x] tiki/publish-client-android/issues/8
- [x] tiki/publish-client-android/issues/9
- [x] tiki/publish-client-android/issues/10

### TikiClient.capture

- [x] tiki/publish-client-android/issues/7
