### ISSUE TITLE
Plan the stories for the deliverable

### ISSUE THREAD

**Issue by Schuler-Gabriel** [tiki/publish#30]
### Reason

Plan the stories for the Tiki.ui deliverable

### Description

Plan and write the step by step process for each on of the following issues:

- tiki/publish-client-android/issues/15
- tiki/publish-client-android#32
- tiki/publish-client-android#33
- tiki/publish-client-android/issues/16
- tiki/publish-client-android/issues/17
- tiki/publish-client-android/issues/18
- tiki/publish-client-android/issues/19

In the planing process the amount of effort to close each issue will be defined

### Success Criteria

- [x] tiki/publish-client-android/issues/15 have all processes planed and written 
- [x] tiki/publish-client-android#32 have all processes planed and written 
- [x] tiki/publish-client-android#33 have all processes planed and written 
- [x] tiki/publish-client-android/issues/16 have all processes planed and written 
- [x] tiki/publish-client-android/issues/17 have all processes planed and written  
- [x] tiki/publish-client-android/issues/18 have all processes planed and written 
- [x] tiki/publish-client-android/issues/19 have all processes planed and written
