### ISSUE TITLE
Capacitor Client Lib

### ISSUE THREAD

**Issue by ricardobrg** [tiki/publish#32]
# TIKI Client Library - Capacitor + Vue Specification

## Technologies Used

1. **Language:** TypeScript
2. **Framework:** Vue.js with Capacitor
3. **Authentication:** AppAuth for OAuth2
4. **Camera Integration:** Capacitor Camera API for receipt image capture
5. **UI Components:** Vue

## Library Structure

1. **TikiClient:** The primary entry point for the TIKI Client Library.

2. **TikiClient.auth:** Handles authentication, token retrieval, revocation, and refresh.

3. **TikiClient.license:** Manages user licenses, including creation, retrieval, revocation, and verification.

4. **TikiClient.email:** Manages email-related operations such as adding, retrieving, and removing email accounts.

5. **TikiClient.capture:** Deals with capturing receipt images, downloading and publishing email receipt data, uploading receipt images, and checking publishing status.

6. **TikiClient.clo:** Handles card-linked offers, including adding cards, retrieving offers, getting user rewards, and publishing transaction information.

### Setup and Configuration

  - [x] tiki/publish-client-capacitor/issues/5
  - [x] tiki/publish-client-capacitor/issues/8
  - [x] tiki/publish-client-capacitor/issues/21

### TikiClient.capture

  - [x] tiki/publish-client-capacitor/issues/1
  - [x] tiki/publish-client-capacitor/issues/2
  - [x] tiki/publish-client-capacitor/issues/3
  - [x] tiki/publish-client-capacitor/issues/6
  - [x] tiki/publish-client-capacitor/issues/10
  - [x] tiki/publish-client-capacitor/issues/11

### TikiClient.auth

  - [x] tiki/publish-client-capacitor/issues/11
  - [x] tiki/publish-client-capacitor/issues/12
  - [x] tiki/publish-client-capacitor/issues/13
  - [x] tiki/publish-client-capacitor/issues/19

### TikiClient.license

  - [x] tiki/publish-client-capacitor/issues/23
  - [x] tiki/publish-client-capacitor/issues/24

### TikiClient

  - [x] `initialize(providerId: string, userId: string, company: CompanyInfo)`: Initializes the TikiClient with parameters.
  - [x] `scan() -> Promise<string>`: Initiates the process of scanning a physical receipt and returns the receipt ID.
