### ISSUE TITLE
TIKI Client Capacitor 1.0

### ISSUE THREAD

**Issue by ricardobrg** [tiki/publish#39]
### Description

First release of the TIKI Client Capacitor library

### Issues

- [x] tiki/publish-client-capacitor/issues/33
- [x] tiki/publish-client-capacitor/issues/34
- [x] tiki/publish-client-capacitor/issues/35
- [x] tiki/publish-client-capacitor/issues/36
- [x] tiki/publish-client-capacitor/issues/37
- [x] tiki/publish-client-capacitor/issues/38
- [x] tiki/publish-client-capacitor/issues/39
- [x] tiki/publish-client-capacitor/issues/40
- [x] tiki/publish-client-capacitor/issues/41
- [x] tiki/publish-client-capacitor/issues/42
- [x] tiki/publish-client-capacitor/issues/44
- [x] tiki/publish-client-capacitor/issues/45
- [x] tiki/publish-client-capacitor/issues/46
- [x] tiki/publish-client-capacitor/issues/47
- [x] tiki/publish-client-capacitor/issues/50
