### ISSUE TITLE
Publish receipts in aws

### ISSUE THREAD

**Issue by ricardobrg** [tiki/publish#40]
### Description

Use Cloud Formation to configure the services to extract data from receipt images.

1. Create an API Gateway to publish and retrieve data
2. Published images should be stored in S3
3. Amazon Textract should be triggered on image upload
4. Extracted data should be transformed to consumable schema
5. Extracted data can be retrieved by receipt id.

### Issues
- [x] tiki/publish-data-receipt/issues/2
- [x] tiki/publish-data-receipt/issues/7
- [x] tiki/publish-data-receipt/issues/8
