### ISSUE TITLE
Get Receipt Data

### ISSUE THREAD

**Issue by MiroBenicio** [tiki/publish#41]
### Description

We should plan and build what is necessary to:
- Our backend service to sanitize the data that comes from the client
- the client side to be able to retrieve receipts data from our data buckets

### Issues

- [x] tiki/publish-data-receipt#3
- [x] tiki/publish-data-receipt#4
- [x] tiki/publish-data-receipt#5
- [x] tiki/publish-data-receipt#6
- [x] tiki/publish-data-receipt#7

### Confirm

- [X] Yeah dude.
