### ISSUE TITLE
Receipt data publishing deployment

### ISSUE THREAD

**Issue by ricardobrg** [tiki/publish#48]
### Description

Deploy the Receipt Data publishing infrastructure, so that users can publish data to TIKI

### Issues

- [x] tiki/publish-data-receipt/issues/12
- [x] tiki/publish-data-receipt/issues/11
- [x] tiki/publish-data-receipt/issues/14
- [x] tiki/core-trail-endpoint/issues/338
