### ISSUE TITLE
Client library planning

### ISSUE THREAD

**Issue by ricardobrg** [tiki/publish#5]
### Description

By moving to an API-centered implementation of our SDKs, we can transform our SDKs into lightweight clients libraries that work as API wrappers to the APIs. This story is to define the structure of the Android, iOS and Capacitor libraries to implement CLO, receipt and rewards features, defined in tiki/apps#67, tiki/apps#59 and tiki/apps#65 .

The focus is to have one or multiple client libraries that makes it easy for the implementer to choose between one or multiple features, without unnecessary overhead.

### Issues

- [x] tiki/capture/issues/11
- [x] tiki/apps#71
- [x] tiki/publish#7
- [x] create the repository for the client lib(s) for Android and iOS 
- [x] tiki/publish-client-android#1
- [x] tiki/publish-client-ios#1
- [x] tiki/publish#10
- [x] #14
- [x] #15
- [x] #12
- [x] #13
