### ISSUE TITLE
Android - Publish Gmail receipts

### ISSUE THREAD

**Issue by ricardobrg** [tiki/publish#57]
### Description

This release will implement the features needed for:
- Gmail account link
- Email scraping
- PDF receipts upload

### Issues

- [ ] tiki/publish-client-android/issues/85
- [ ] tiki/publish-client-android/issues/86
- [ ] tiki/publish-client-android/issues/87
- [ ] tiki/publish-client-android/issues/88
- [ ] tiki/publish-client-android/issues/89
